import { Body, Controller, Get, Inject, Param, Post, Put, Req, UnauthorizedException, UseFilters } from '@nestjs/common';
import { NeedLogin } from '@lark-apaas/fullstack-nestjs-core';
import type { Request } from 'express';
import { PaperProjectExceptionFilter } from './paper-project.exception-filter';
import { PaperProjectRepository } from './paper-project.repository';
import { PaperPlanningService } from './paper-planning.service';
import { PaperWorkflowService } from './paper-workflow.service';
import { PaperSourceService } from './paper-source.service';
import { PaperGenerationService } from './paper-generation.service';
import { PaperProjectError } from './paper-project.errors';

export class PaperWorkflowController{
  constructor(private readonly projects:PaperProjectRepository,private readonly planning:PaperPlanningService,private readonly workflow:PaperWorkflowService,private readonly sources:PaperSourceService,private readonly generation:PaperGenerationService){}
  private user(req:Request){const id=req.userContext?.userId;if(!id)throw new UnauthorizedException('Authentication is required.');return id;}
  private async ownedSection(userId:string,projectId:string,sectionId:string){const section=await this.projects.getSection(userId,projectId,sectionId);if(!section)throw new PaperProjectError('PAPER_PROJECT_NOT_FOUND','Paper section was not found.');return section;}
  topics(req:Request,p:string,b:unknown){return this.planning.generateTopics(this.user(req),p,b);} plan(req:Request,p:string,b:unknown){return this.planning.generateResearchPlan(this.user(req),p,b);} outlineProposal(req:Request,p:string,b:unknown){return this.planning.generateOutline(this.user(req),p,b);}
  async outline(req:Request,p:string){const user=this.user(req);const[project,nodes]=await Promise.all([this.projects.require(user,p),this.projects.listOutline(user,p,true)]);return{nodes,lockVersion:project.lockVersion};} saveOutline(req:Request,p:string,b:unknown){return this.workflow.saveOutline(this.user(req),p,b);}
  listSources(req:Request,p:string){return this.sources.list(this.user(req),p);} saveSources(req:Request,p:string,b:unknown){return this.sources.replace(this.user(req),p,b);}
  async section(req:Request,p:string,s:string){const user=this.user(req);const section=await this.ownedSection(user,p,s);const[revisions,outline]=await Promise.all([this.projects.listRevisions(user,s),this.projects.listOutline(user,p,true)]);return{section,outlineNode:outline.find(node=>node.id===section.outlineNodeId)??null,currentRevision:revisions[0]??null};}
  async revisions(req:Request,p:string,s:string){const user=this.user(req);await this.ownedSection(user,p,s);return this.projects.listRevisions(user,s);} async revision(req:Request,p:string,s:string,r:string){const user=this.user(req);await this.ownedSection(user,p,s);const revision=await this.projects.getRevision(user,s,r);if(!revision)throw new PaperProjectError('PAPER_PROJECT_NOT_FOUND','Paper revision was not found.');return revision;}
  saveRevision(req:Request,p:string,s:string,b:unknown){return this.workflow.saveUserRevision(this.user(req),p,s,b);} generate(req:Request,p:string,s:string,b:unknown){return this.generation.generate(this.user(req),p,s,b);}
  restore(req:Request,p:string,s:string,b:unknown){return this.workflow.restoreRevision(this.user(req),p,s,b);} remap(req:Request,p:string,s:string,b:unknown){return this.workflow.remap(this.user(req),p,s,b);}
  async evidence(req:Request,p:string,s:string,r:string){const user=this.user(req);await this.ownedSection(user,p,s);const revision=await this.projects.getRevision(user,s,r);if(!revision)throw new PaperProjectError('PAPER_PROJECT_NOT_FOUND','Paper revision was not found.');return{citations:revision.citations,bibliography:revision.bibliography,evidenceTrace:revision.evidenceTrace,supportState:revision.supportState,warnings:revision.warnings};}
}
Controller('api/paper-projects')(PaperWorkflowController);UseFilters(PaperProjectExceptionFilter)(PaperWorkflowController);[PaperProjectRepository,PaperPlanningService,PaperWorkflowService,PaperSourceService,PaperGenerationService].forEach((token,index)=>Inject(token)(PaperWorkflowController,undefined,index));
for(const name of ['topics','plan','outlineProposal','outline','saveOutline','listSources','saveSources','section','revisions','revision','saveRevision','generate','restore','remap','evidence'] as const)NeedLogin()(PaperWorkflowController.prototype,name,Object.getOwnPropertyDescriptor(PaperWorkflowController.prototype,name)!);
const route=(decorator:MethodDecorator,name:keyof PaperWorkflowController,params:Array<[ReturnType<typeof Req>|ReturnType<typeof Body>|ReturnType<typeof Param>,number]>)=>{decorator(PaperWorkflowController.prototype,name,Object.getOwnPropertyDescriptor(PaperWorkflowController.prototype,name)!);for(const[param,index]of params)(param as ParameterDecorator)(PaperWorkflowController.prototype,name,index);};
route(Post(':projectId/topics/generate'),'topics',[[Req(),0],[Param('projectId'),1],[Body(),2]]);route(Post(':projectId/research-plan/generate'),'plan',[[Req(),0],[Param('projectId'),1],[Body(),2]]);route(Post(':projectId/outline/generate'),'outlineProposal',[[Req(),0],[Param('projectId'),1],[Body(),2]]);route(Get(':projectId/outline'),'outline',[[Req(),0],[Param('projectId'),1]]);route(Put(':projectId/outline'),'saveOutline',[[Req(),0],[Param('projectId'),1],[Body(),2]]);route(Get(':projectId/sources'),'listSources',[[Req(),0],[Param('projectId'),1]]);route(Put(':projectId/sources'),'saveSources',[[Req(),0],[Param('projectId'),1],[Body(),2]]);route(Get(':projectId/sections/:sectionId'),'section',[[Req(),0],[Param('projectId'),1],[Param('sectionId'),2]]);route(Get(':projectId/sections/:sectionId/revisions'),'revisions',[[Req(),0],[Param('projectId'),1],[Param('sectionId'),2]]);route(Get(':projectId/sections/:sectionId/revisions/:revisionId'),'revision',[[Req(),0],[Param('projectId'),1],[Param('sectionId'),2],[Param('revisionId'),3]]);route(Post(':projectId/sections/:sectionId/revisions'),'saveRevision',[[Req(),0],[Param('projectId'),1],[Param('sectionId'),2],[Body(),3]]);route(Post(':projectId/sections/:sectionId/revisions/restore'),'restore',[[Req(),0],[Param('projectId'),1],[Param('sectionId'),2],[Body(),3]]);route(Post(':projectId/sections/:sectionId/remap'),'remap',[[Req(),0],[Param('projectId'),1],[Param('sectionId'),2],[Body(),3]]);route(Post(':projectId/sections/:sectionId/generations'),'generate',[[Req(),0],[Param('projectId'),1],[Param('sectionId'),2],[Body(),3]]);route(Get(':projectId/sections/:sectionId/revisions/:revisionId/evidence'),'evidence',[[Req(),0],[Param('projectId'),1],[Param('sectionId'),2],[Param('revisionId'),3]]);
